import { config } from "dotenv";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";
import bcrypt from "bcryptjs";
import { PrismaClient, Difficulty, Role, MenuItemType } from "@prisma/client";

const __dirname = dirname(fileURLToPath(import.meta.url));
config({ path: resolve(__dirname, "../../.env") });

const prisma = new PrismaClient();

const IMG = {
  restaurant: {
    lagosFire: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
    jollofHouse: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    suyaSpot: "https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&q=80",
    pastaBar: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    dragonWok: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
    spiceRoute: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80",
    burgerYard: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=800&q=80",
    oliveGrove: "https://images.unsplash.com/photo-1559339352-11d22aa27d61?w=800&q=80",
    harbourGrill: "https://images.unsplash.com/photo-1559339352-11d22aa27d61?w=800&q=80",
    kanoKitchen: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&q=80",
    ibadanBowl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=800&q=80",
    capitalPlate: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80",
  },
  food: {
    jollof: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&q=80",
    suya: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80",
    egusi: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&q=80",
    poundedYam: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600&q=80",
    shawarma: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80",
    pasta: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80",
    pizza: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80",
    burger: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80",
    seafood: "https://images.unsplash.com/photo-1559339352-11d22aa27d61?w=600&q=80",
    friedRice: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&q=80",
    salad: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80",
    drink: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80",
    dessert: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&q=80",
    noodles: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80",
    curry: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&q=80",
    bread: "/breads/wrapped-studio.png",
    baguette: "/breads/wheat-studio.png",
    honeyBread: "/breads/honey-studio.png",
    chocolateBread: "/breads/chocolate-studio.png",
    coconutBread: "/breads/coconut-studio.png",
  },
};

const WEEKDAY_HOURS = {
  monday: { open: "10:00", close: "22:00" },
  tuesday: { open: "10:00", close: "22:00" },
  wednesday: { open: "10:00", close: "22:00" },
  thursday: { open: "10:00", close: "22:00" },
  friday: { open: "10:00", close: "23:00" },
  saturday: { open: "11:00", close: "23:00" },
  sunday: { open: "12:00", close: "21:00" },
};

async function clearData() {
  await prisma.menuPlanItem.deleteMany();
  await prisma.menuPlan.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.pairing.deleteMany();
  await prisma.breadIngredient.deleteMany();
  await prisma.breadNutrition.deleteMany();
  await prisma.recipeIngredient.deleteMany();
  await prisma.menuItem.deleteMany();
  await prisma.restaurantCuisine.deleteMany();
  await prisma.recipe.deleteMany();
  await prisma.bread.deleteMany();
  await prisma.restaurant.deleteMany();
  await prisma.cuisine.deleteMany();
  await prisma.user.deleteMany();
}

async function seedUsers() {
  const adminHash = await bcrypt.hash("Admin123!", 10);
  const userHash = await bcrypt.hash("User1234!", 10);

  const admin = await prisma.user.create({
    data: {
      name: "ChowSmart Admin",
      email: "admin@chowsmart.app",
      passwordHash: adminHash,
      role: Role.ADMIN,
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    },
  });

  const user = await prisma.user.create({
    data: {
      name: "Ada Okonkwo",
      email: "user@chowsmart.app",
      passwordHash: userHash,
      role: Role.USER,
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    },
  });

  return { admin, user };
}

async function seedCuisines() {
  const names = [
    "Nigerian",
    "Italian",
    "Chinese",
    "Indian",
    "American",
    "Mediterranean",
    "Continental",
    "African",
    "Japanese",
  ];

  const cuisines = [];
  for (const name of names) {
    const cuisine = await prisma.cuisine.create({
      data: {
        name,
        slug: name.toLowerCase().replace(/\s+/g, "-"),
      },
    });
    cuisines.push(cuisine);
  }
  return Object.fromEntries(cuisines.map((c) => [c.slug, c]));
}

async function seedRestaurants(cuisines: Record<string, { id: string; slug: string }>) {
  const restaurantsData = [
    {
      name: "Mama Put Kitchen",
      slug: "mama-put-kitchen",
      description:
        "A beloved Lagos institution serving smoky party jollof, pepper soup, and home-style Nigerian stews in a lively Victoria Island setting.",
      address: "14 Adeola Odeku Street, Victoria Island",
      city: "Lagos",
      state: "Lagos",
      latitude: 6.4281,
      longitude: 3.4219,
      phone: "+234 801 234 5601",
      email: "hello@mamaput.ng",
      website: "https://mamaput.ng",
      priceRange: "₦₦",
      rating: 4.7,
      image: IMG.restaurant.jollofHouse,
      featured: true,
      cuisineSlugs: ["nigerian", "african"],
    },
    {
      name: "Suya Republic",
      slug: "suya-republic",
      description:
        "Charcoal-grilled suya, kilishi, and spicy sides served late into the night — a Lekki favourite for spice lovers.",
      address: "22 Admiralty Way, Lekki Phase 1",
      city: "Lagos",
      state: "Lagos",
      latitude: 6.4474,
      longitude: 3.4721,
      phone: "+234 802 345 6702",
      priceRange: "₦",
      rating: 4.6,
      image: IMG.restaurant.suyaSpot,
      featured: true,
      cuisineSlugs: ["nigerian", "african"],
    },
    {
      name: "Trattoria Ikeja",
      slug: "trattoria-ikeja",
      description:
        "Wood-fired pizzas, fresh pasta, and Italian classics with a West African pantry twist in the heart of Ikeja.",
      address: "8 Allen Avenue, Ikeja",
      city: "Lagos",
      state: "Lagos",
      latitude: 6.6018,
      longitude: 3.3515,
      phone: "+234 803 456 7803",
      email: "book@trattoriaikeja.com",
      priceRange: "₦₦₦",
      rating: 4.5,
      image: IMG.restaurant.pastaBar,
      featured: false,
      cuisineSlugs: ["italian", "continental"],
    },
    {
      name: "Dragon Wok Abuja",
      slug: "dragon-wok-abuja",
      description:
        "Cantonese and Sichuan favourites prepared wok-hot — dumplings, fried rice, and aromatic stir-fries in Wuse II.",
      address: "5 Aminu Kano Crescent, Wuse II",
      city: "Abuja",
      state: "FCT",
      latitude: 9.0765,
      longitude: 7.4808,
      phone: "+234 804 567 8904",
      priceRange: "₦₦",
      rating: 4.4,
      image: IMG.restaurant.dragonWok,
      featured: true,
      cuisineSlugs: ["chinese"],
    },
    {
      name: "Spice Route Maitama",
      slug: "spice-route-maitama",
      description:
        "North Indian curries, tandoori breads, and fragrant biryanis in an elegant Maitama dining room.",
      address: "12 Aguiyi Ironsi Street, Maitama",
      city: "Abuja",
      state: "FCT",
      latitude: 9.0852,
      longitude: 7.4951,
      phone: "+234 805 678 9015",
      website: "https://spiceroute.ng",
      priceRange: "₦₦₦",
      rating: 4.8,
      image: IMG.restaurant.spiceRoute,
      featured: true,
      cuisineSlugs: ["indian"],
    },
    {
      name: "Harbour Grill PH",
      slug: "harbour-grill-ph",
      description:
        "Fresh Gulf of Guinea seafood, grilled prawns, and pepper soup overlooking the Port Harcourt waterfront.",
      address: "3 Trans Amadi Road, Trans Amadi",
      city: "Port Harcourt",
      state: "Rivers",
      latitude: 4.8156,
      longitude: 7.0498,
      phone: "+234 806 789 0126",
      priceRange: "₦₦₦",
      rating: 4.6,
      image: IMG.restaurant.harbourGrill,
      featured: true,
      cuisineSlugs: ["nigerian", "continental", "mediterranean"],
    },
    {
      name: "Bodija Bowl",
      slug: "bodija-bowl",
      description:
        "Comforting amala, ewedu, gbegiri, and Ibadan-style peppersoup in a casual Bodija neighbourhood spot.",
      address: "17 Bodija Market Road, Bodija",
      city: "Ibadan",
      state: "Oyo",
      latitude: 7.4378,
      longitude: 3.9135,
      phone: "+234 807 890 1237",
      priceRange: "₦",
      rating: 4.5,
      image: IMG.restaurant.ibadanBowl,
      featured: false,
      cuisineSlugs: ["nigerian", "african"],
    },
    {
      name: "Yankari Burger Yard",
      slug: "yankari-burger-yard",
      description:
        "Smash burgers, loaded fries, and cold drinks with American diner energy in the Sabon Gari district.",
      address: "9 Club Road, Sabon Gari",
      city: "Kano",
      state: "Kano",
      latitude: 12.0022,
      longitude: 8.522,
      phone: "+234 808 901 2348",
      priceRange: "₦₦",
      rating: 4.3,
      image: IMG.restaurant.burgerYard,
      featured: false,
      cuisineSlugs: ["american"],
    },
    {
      name: "Olive Grove Lounge",
      slug: "olive-grove-lounge",
      description:
        "Mediterranean mezze, grilled fish, and olive-oil-forward plates in a relaxed Ikoyi lounge.",
      address: "6 MacDonald Road, Ikoyi",
      city: "Lagos",
      state: "Lagos",
      latitude: 6.4541,
      longitude: 3.4358,
      phone: "+234 809 012 3459",
      email: "reservations@olivegrove.ng",
      priceRange: "₦₦₦",
      rating: 4.7,
      image: IMG.restaurant.oliveGrove,
      featured: true,
      cuisineSlugs: ["mediterranean", "continental"],
    },
    {
      name: "Capital Plate",
      slug: "capital-plate",
      description:
        "Contemporary African tasting plates and continental mains — a polished Garki destination for business lunches.",
      address: "21 Moshood Abiola Way, Garki",
      city: "Abuja",
      state: "FCT",
      latitude: 9.0305,
      longitude: 7.4869,
      phone: "+234 810 123 4560",
      priceRange: "₦₦₦",
      rating: 4.6,
      image: IMG.restaurant.capitalPlate,
      featured: false,
      cuisineSlugs: ["african", "continental", "nigerian"],
    },
    {
      name: "Kano Kitchen Collective",
      slug: "kano-kitchen-collective",
      description:
        "Northern Nigerian staples — tuwo, miyan kuka, masa, and slow-cooked meats — from a family kitchen in Nassarawa GRA.",
      address: "4 Ahmadu Bello Way, Nassarawa GRA",
      city: "Kano",
      state: "Kano",
      latitude: 11.9914,
      longitude: 8.5311,
      phone: "+234 811 234 5671",
      priceRange: "₦₦",
      rating: 4.4,
      image: IMG.restaurant.kanoKitchen,
      featured: false,
      cuisineSlugs: ["nigerian", "african"],
    },
    {
      name: "Garden City Bistro",
      slug: "garden-city-bistro",
      description:
        "Continental brunch, pasta, and light seafood plates in Port Harcourt's GRA — ideal for weekend gatherings.",
      address: "11 Tombia Street, GRA Phase 2",
      city: "Port Harcourt",
      state: "Rivers",
      latitude: 4.8472,
      longitude: 7.0128,
      phone: "+234 812 345 6782",
      priceRange: "₦₦",
      rating: 4.2,
      image: IMG.restaurant.lagosFire,
      featured: false,
      cuisineSlugs: ["continental", "italian", "mediterranean"],
    },
    {
      name: "Sakura Lagos",
      slug: "sakura-lagos",
      description:
        "Fresh sushi, ramen, and teppanyaki in a calm Victoria Island dining room — Lagos’s go-to for Japanese comfort.",
      address: "19A Ozumba Mbadiwe Avenue, Victoria Island",
      city: "Lagos",
      state: "Lagos",
      latitude: 6.4285,
      longitude: 3.4351,
      phone: "+234 813 456 7893",
      email: "hello@sakuralagos.ng",
      website: "https://sakuralagos.ng",
      priceRange: "₦₦₦",
      rating: 4.7,
      image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80",
      featured: true,
      cuisineSlugs: ["japanese"],
    },
  ];

  const restaurants = [];
  for (const r of restaurantsData) {
    const { cuisineSlugs, ...data } = r;
    const restaurant = await prisma.restaurant.create({
      data: {
        ...data,
        country: "Nigeria",
        openingHours: WEEKDAY_HOURS,
        cuisines: {
          create: cuisineSlugs.map((slug) => ({
            cuisineId: cuisines[slug].id,
          })),
        },
      },
    });
    restaurants.push(restaurant);
  }
  return Object.fromEntries(restaurants.map((r) => [r.slug, r]));
}

async function seedMenuItems(restaurants: Record<string, { id: string }>) {
  const items: Array<{
    restaurantSlug: string;
    name: string;
    description: string;
    price: number;
    category: string;
    image: string;
    ingredients: string[];
    allergens: string[];
    calories: number;
    featured?: boolean;
  }> = [
    {
      restaurantSlug: "mama-put-kitchen",
      name: "Party Jollof Rice",
      description: "Smoky tomato-pepper jollof rice cooked over open fire with chicken stock and thyme.",
      price: 3500,
      category: "Mains",
      image: IMG.food.jollof,
      ingredients: ["long-grain rice", "tomato", "scotch bonnet", "onion", "thyme", "stock"],
      allergens: [],
      calories: 520,
      featured: true,
    },
    {
      restaurantSlug: "mama-put-kitchen",
      name: "Egusi Soup with Pounded Yam",
      description: "Ground melon-seed soup with spinach, assorted meats, and smooth pounded yam.",
      price: 4500,
      category: "Mains",
      image: IMG.food.egusi,
      ingredients: ["egusi", "spinach", "beef", "stockfish", "palm oil", "yam"],
      allergens: ["fish"],
      calories: 780,
      featured: true,
    },
    {
      restaurantSlug: "mama-put-kitchen",
      name: "Pepper Soup (Goat)",
      description: "Aromatic goat pepper soup with uziza, scent leaf, and fresh chilli.",
      price: 3200,
      category: "Starters",
      image: IMG.food.egusi,
      ingredients: ["goat", "uziza", "scent leaf", "pepper", "onion"],
      allergens: [],
      calories: 310,
    },
    {
      restaurantSlug: "mama-put-kitchen",
      name: "Moi Moi",
      description: "Steamed bean pudding wrapped in leaves with boiled egg and fish flakes.",
      price: 1500,
      category: "Sides",
      image: IMG.food.friedRice,
      ingredients: ["beans", "pepper", "onion", "egg", "fish"],
      allergens: ["egg", "fish"],
      calories: 280,
    },
    {
      restaurantSlug: "mama-put-kitchen",
      name: "Zobo Drink",
      description: "Chilled hibiscus drink infused with ginger, pineapple, and cloves.",
      price: 800,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["hibiscus", "ginger", "pineapple", "cloves"],
      allergens: [],
      calories: 90,
    },
    {
      restaurantSlug: "suya-republic",
      name: "Classic Beef Suya",
      description: "Thinly sliced beef dusted with yaji spice blend and grilled over charcoal.",
      price: 2500,
      category: "Mains",
      image: IMG.food.suya,
      ingredients: ["beef", "groundnut", "ginger", "garlic", "cayenne", "onion"],
      allergens: ["peanuts"],
      calories: 420,
      featured: true,
    },
    {
      restaurantSlug: "suya-republic",
      name: "Chicken Suya Skewers",
      description: "Marinated chicken skewers with suya spice and fresh tomato-onion salad.",
      price: 2800,
      category: "Mains",
      image: IMG.food.suya,
      ingredients: ["chicken", "suya spice", "tomato", "onion"],
      allergens: ["peanuts"],
      calories: 380,
    },
    {
      restaurantSlug: "suya-republic",
      name: "Kilishi Plate",
      description: "Dried spicy beef jerky with cucumber and pepper sauce on the side.",
      price: 3000,
      category: "Starters",
      image: IMG.food.suya,
      ingredients: ["beef", "pepper", "spices"],
      allergens: [],
      calories: 290,
    },
    {
      restaurantSlug: "suya-republic",
      name: "Roasted Plantain",
      description: "Charred ripe plantain with a light sprinkle of chilli salt.",
      price: 1200,
      category: "Sides",
      image: IMG.food.friedRice,
      ingredients: ["plantain", "salt", "chilli"],
      allergens: [],
      calories: 220,
    },
    {
      restaurantSlug: "trattoria-ikeja",
      name: "Margherita Pizza",
      description: "San Marzano tomato, fresh mozzarella, basil, and olive oil on a blistered crust.",
      price: 6500,
      category: "Mains",
      image: IMG.food.pizza,
      ingredients: ["flour", "tomato", "mozzarella", "basil", "olive oil"],
      allergens: ["gluten", "dairy"],
      calories: 680,
      featured: true,
    },
    {
      restaurantSlug: "trattoria-ikeja",
      name: "Spaghetti Aglio e Olio",
      description: "Garlic, chilli flakes, parsley, and extra-virgin olive oil tossed with al dente spaghetti.",
      price: 5500,
      category: "Mains",
      image: IMG.food.pasta,
      ingredients: ["spaghetti", "garlic", "chilli", "parsley", "olive oil"],
      allergens: ["gluten"],
      calories: 540,
    },
    {
      restaurantSlug: "trattoria-ikeja",
      name: "Bruschetta Trio",
      description: "Toasted baguette topped with tomato-basil, mushroom, and roasted pepper spreads.",
      price: 3200,
      category: "Starters",
      image: IMG.food.baguette,
      ingredients: ["baguette", "tomato", "mushroom", "pepper", "garlic"],
      allergens: ["gluten"],
      calories: 310,
    },
    {
      restaurantSlug: "trattoria-ikeja",
      name: "Tiramisu",
      description: "Espresso-soaked ladyfingers layered with mascarpone cream and cocoa.",
      price: 3500,
      category: "Desserts",
      image: IMG.food.dessert,
      ingredients: ["mascarpone", "espresso", "ladyfingers", "cocoa", "egg"],
      allergens: ["dairy", "egg", "gluten"],
      calories: 450,
    },
    {
      restaurantSlug: "dragon-wok-abuja",
      name: "Wok Fried Rice",
      description: "Egg fried rice with prawns, spring onion, and light soy.",
      price: 4000,
      category: "Mains",
      image: IMG.food.friedRice,
      ingredients: ["rice", "egg", "prawn", "spring onion", "soy sauce"],
      allergens: ["egg", "shellfish", "soy"],
      calories: 560,
      featured: true,
    },
    {
      restaurantSlug: "dragon-wok-abuja",
      name: "Kung Pao Chicken",
      description: "Diced chicken with peanuts, dried chilli, and a glossy sweet-savoury sauce.",
      price: 5200,
      category: "Mains",
      image: IMG.food.noodles,
      ingredients: ["chicken", "peanuts", "chilli", "soy", "garlic"],
      allergens: ["peanuts", "soy"],
      calories: 610,
    },
    {
      restaurantSlug: "dragon-wok-abuja",
      name: "Steamed Dumplings",
      description: "Pork and cabbage dumplings served with black vinegar dipping sauce.",
      price: 2800,
      category: "Starters",
      image: IMG.food.noodles,
      ingredients: ["pork", "cabbage", "flour", "ginger"],
      allergens: ["gluten"],
      calories: 340,
    },
    {
      restaurantSlug: "dragon-wok-abuja",
      name: "Jasmine Tea",
      description: "Hot jasmine green tea — light, floral, and cleansing after a spicy meal.",
      price: 900,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["jasmine tea"],
      allergens: [],
      calories: 5,
    },
    {
      restaurantSlug: "spice-route-maitama",
      name: "Chicken Biryani",
      description: "Layered basmati rice with spiced chicken, saffron, and fried onions.",
      price: 5800,
      category: "Mains",
      image: IMG.food.curry,
      ingredients: ["basmati", "chicken", "yoghurt", "saffron", "onion", "spices"],
      allergens: ["dairy"],
      calories: 720,
      featured: true,
    },
    {
      restaurantSlug: "spice-route-maitama",
      name: "Butter Chicken",
      description: "Tandoori chicken simmered in a creamy tomato-cashew gravy.",
      price: 6200,
      category: "Mains",
      image: IMG.food.curry,
      ingredients: ["chicken", "tomato", "cream", "cashew", "butter", "garam masala"],
      allergens: ["dairy", "tree nuts"],
      calories: 690,
    },
    {
      restaurantSlug: "spice-route-maitama",
      name: "Garlic Naan",
      description: "Soft tandoor-baked naan brushed with garlic butter and coriander.",
      price: 1500,
      category: "Sides",
      image: IMG.food.bread,
      ingredients: ["flour", "yeast", "garlic", "butter"],
      allergens: ["gluten", "dairy"],
      calories: 260,
    },
    {
      restaurantSlug: "spice-route-maitama",
      name: "Mango Lassi",
      description: "Chilled yoghurt drink blended with ripe mango and a hint of cardamom.",
      price: 1800,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["yoghurt", "mango", "cardamom", "sugar"],
      allergens: ["dairy"],
      calories: 210,
    },
    {
      restaurantSlug: "harbour-grill-ph",
      name: "Grilled Prawns",
      description: "Tiger prawns grilled with garlic-chilli butter and served with lime.",
      price: 7500,
      category: "Mains",
      image: IMG.food.seafood,
      ingredients: ["prawns", "garlic", "butter", "chilli", "lime"],
      allergens: ["shellfish", "dairy"],
      calories: 480,
      featured: true,
    },
    {
      restaurantSlug: "harbour-grill-ph",
      name: "Catfish Pepper Soup",
      description: "Fresh catfish in a light, fiery broth with scent leaf and calabash nutmeg.",
      price: 4200,
      category: "Starters",
      image: IMG.food.seafood,
      ingredients: ["catfish", "pepper", "scent leaf", "ehuru"],
      allergens: ["fish"],
      calories: 290,
    },
    {
      restaurantSlug: "harbour-grill-ph",
      name: "Seafood Okro Soup",
      description: "Okro soup thickened with periwinkle, prawns, and smoked fish.",
      price: 5500,
      category: "Mains",
      image: IMG.food.egusi,
      ingredients: ["okro", "periwinkle", "prawn", "smoked fish", "palm oil"],
      allergens: ["shellfish", "fish"],
      calories: 540,
    },
    {
      restaurantSlug: "harbour-grill-ph",
      name: "Coconut Water Cooler",
      description: "Fresh coconut water with mint and a squeeze of lime.",
      price: 1200,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["coconut water", "mint", "lime"],
      allergens: [],
      calories: 60,
    },
    {
      restaurantSlug: "bodija-bowl",
      name: "Amala with Ewedu & Gbegiri",
      description: "Soft yam-flour swallow with green ewedu and creamy bean soup, plus assorted meat.",
      price: 2800,
      category: "Mains",
      image: IMG.food.poundedYam,
      ingredients: ["yam flour", "ewedu", "beans", "locust bean", "meat"],
      allergens: [],
      calories: 650,
      featured: true,
    },
    {
      restaurantSlug: "bodija-bowl",
      name: "Ofada Rice & Ayamase",
      description: "Local ofada rice with green pepper stew, boiled egg, and assorted meats.",
      price: 3200,
      category: "Mains",
      image: IMG.food.jollof,
      ingredients: ["ofada rice", "green pepper", "palm oil", "egg", "meat"],
      allergens: ["egg"],
      calories: 710,
    },
    {
      restaurantSlug: "bodija-bowl",
      name: "Pounded Yam & Efo Riro",
      description: "Smooth pounded yam with rich spinach stew and smoked fish.",
      price: 3500,
      category: "Mains",
      image: IMG.food.poundedYam,
      ingredients: ["yam", "spinach", "pepper", "smoked fish", "palm oil"],
      allergens: ["fish"],
      calories: 740,
    },
    {
      restaurantSlug: "yankari-burger-yard",
      name: "Classic Smash Burger",
      description: "Double smash patties, cheddar, pickles, and house sauce on a toasted bun.",
      price: 4500,
      category: "Mains",
      image: IMG.food.burger,
      ingredients: ["beef", "cheddar", "bun", "pickle", "onion", "sauce"],
      allergens: ["gluten", "dairy"],
      calories: 820,
      featured: true,
    },
    {
      restaurantSlug: "yankari-burger-yard",
      name: "Loaded Fries",
      description: "Crispy fries topped with cheese sauce, suya spice, and spring onion.",
      price: 2500,
      category: "Sides",
      image: IMG.food.burger,
      ingredients: ["potato", "cheese", "suya spice", "spring onion"],
      allergens: ["dairy", "peanuts"],
      calories: 510,
    },
    {
      restaurantSlug: "yankari-burger-yard",
      name: "Chocolate Milkshake",
      description: "Thick chocolate shake blended with vanilla ice cream.",
      price: 2200,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["milk", "chocolate", "ice cream"],
      allergens: ["dairy"],
      calories: 480,
    },
    {
      restaurantSlug: "olive-grove-lounge",
      name: "Mezze Platter",
      description: "Hummus, baba ganoush, olives, flatbread, and marinated feta.",
      price: 4800,
      category: "Starters",
      image: IMG.food.salad,
      ingredients: ["chickpea", "aubergine", "olive", "feta", "flatbread"],
      allergens: ["gluten", "dairy", "sesame"],
      calories: 520,
      featured: true,
    },
    {
      restaurantSlug: "olive-grove-lounge",
      name: "Grilled Sea Bass",
      description: "Whole sea bass with lemon, herbs, and roasted Mediterranean vegetables.",
      price: 8900,
      category: "Mains",
      image: IMG.food.seafood,
      ingredients: ["sea bass", "lemon", "herbs", "courgette", "tomato"],
      allergens: ["fish"],
      calories: 490,
    },
    {
      restaurantSlug: "olive-grove-lounge",
      name: "Greek Salad",
      description: "Cucumber, tomato, red onion, olives, and feta with oregano dressing.",
      price: 3200,
      category: "Sides",
      image: IMG.food.salad,
      ingredients: ["cucumber", "tomato", "onion", "olive", "feta"],
      allergens: ["dairy"],
      calories: 280,
    },
    {
      restaurantSlug: "olive-grove-lounge",
      name: "Baklava",
      description: "Layered filo pastry with walnuts, pistachios, and honey syrup.",
      price: 2800,
      category: "Desserts",
      image: IMG.food.dessert,
      ingredients: ["filo", "walnut", "pistachio", "honey", "butter"],
      allergens: ["gluten", "dairy", "tree nuts"],
      calories: 390,
    },
    {
      restaurantSlug: "capital-plate",
      name: "Chicken Shawarma Wrap",
      description: "Spiced chicken shawarma with garlic sauce, pickles, and fries in warm flatbread.",
      price: 3800,
      category: "Mains",
      image: IMG.food.shawarma,
      ingredients: ["chicken", "flatbread", "garlic sauce", "pickle", "cabbage"],
      allergens: ["gluten", "dairy"],
      calories: 640,
      featured: true,
    },
    {
      restaurantSlug: "capital-plate",
      name: "Grilled Tilapia & Plantain",
      description: "Whole grilled tilapia with spicy pepper sauce and fried plantain.",
      price: 5200,
      category: "Mains",
      image: IMG.food.seafood,
      ingredients: ["tilapia", "pepper", "onion", "plantain"],
      allergens: ["fish"],
      calories: 580,
    },
    {
      restaurantSlug: "capital-plate",
      name: "Chapman Cocktail",
      description: "Nigerian classic soft cocktail with Fanta, Sprite, bitters, and cucumber.",
      price: 2000,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["Fanta", "Sprite", "Angostura", "cucumber", "orange"],
      allergens: [],
      calories: 180,
    },
    {
      restaurantSlug: "kano-kitchen-collective",
      name: "Tuwo Shinkafa & Miyan Kuka",
      description: "Rice swallow with baobab-leaf soup and soft chunks of beef.",
      price: 2600,
      category: "Mains",
      image: IMG.food.poundedYam,
      ingredients: ["rice flour", "baobab leaf", "beef", "locust bean"],
      allergens: [],
      calories: 620,
    },
    {
      restaurantSlug: "kano-kitchen-collective",
      name: "Masa with Miyan Taushe",
      description: "Fermented rice cakes served with pumpkin stew and grilled meat.",
      price: 2400,
      category: "Mains",
      image: IMG.food.jollof,
      ingredients: ["rice", "pumpkin", "pepper", "meat", "yeast"],
      allergens: [],
      calories: 540,
      featured: true,
    },
    {
      restaurantSlug: "kano-kitchen-collective",
      name: "Fura da Nono",
      description: "Millet balls in lightly fermented cow milk — a Northern classic cooler.",
      price: 1000,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["millet", "milk", "ginger", "cloves"],
      allergens: ["dairy"],
      calories: 220,
    },
    {
      restaurantSlug: "garden-city-bistro",
      name: "Penne Arrabbiata",
      description: "Penne in a spicy tomato sauce with garlic, chilli, and parsley.",
      price: 4800,
      category: "Mains",
      image: IMG.food.pasta,
      ingredients: ["penne", "tomato", "garlic", "chilli", "parsley"],
      allergens: ["gluten"],
      calories: 560,
    },
    {
      restaurantSlug: "garden-city-bistro",
      name: "Caesar Salad",
      description: "Crisp romaine, Parmesan, croutons, and creamy Caesar dressing.",
      price: 3500,
      category: "Starters",
      image: IMG.food.salad,
      ingredients: ["romaine", "parmesan", "crouton", "anchovy", "egg"],
      allergens: ["gluten", "dairy", "fish", "egg"],
      calories: 390,
    },
    {
      restaurantSlug: "garden-city-bistro",
      name: "Lemon Cheesecake",
      description: "Baked cheesecake with lemon zest and a biscuit base.",
      price: 3000,
      category: "Desserts",
      image: IMG.food.dessert,
      ingredients: ["cream cheese", "lemon", "biscuit", "sugar", "egg"],
      allergens: ["dairy", "gluten", "egg"],
      calories: 420,
    },
    {
      restaurantSlug: "sakura-lagos",
      name: "Salmon Nigiri Set",
      description: "Six pieces of fresh salmon nigiri with wasabi, pickled ginger, and soy.",
      price: 8500,
      category: "Mains",
      image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80",
      ingredients: ["sushi rice", "salmon", "nori", "wasabi", "soy sauce"],
      allergens: ["fish", "soy"],
      calories: 420,
      featured: true,
    },
    {
      restaurantSlug: "sakura-lagos",
      name: "Tonkotsu Ramen",
      description: "Rich pork-bone broth with chashu, soft egg, menma, and spring onion.",
      price: 7200,
      category: "Mains",
      image: IMG.food.noodles,
      ingredients: ["ramen noodles", "pork broth", "chashu", "egg", "spring onion"],
      allergens: ["gluten", "egg", "soy"],
      calories: 680,
      featured: true,
    },
    {
      restaurantSlug: "sakura-lagos",
      name: "Edamame",
      description: "Steamed soybeans tossed with sea salt — a light starter to share.",
      price: 2200,
      category: "Starters",
      image: IMG.food.salad,
      ingredients: ["edamame", "sea salt"],
      allergens: ["soy"],
      calories: 180,
    },
    {
      restaurantSlug: "sakura-lagos",
      name: "Matcha Latte",
      description: "Ceremonial-grade matcha whisked with steamed milk.",
      price: 2800,
      category: "Drinks",
      image: IMG.food.drink,
      ingredients: ["matcha", "milk"],
      allergens: ["dairy"],
      calories: 160,
    },
  ];

  const created = [];
  for (const item of items) {
    const { restaurantSlug, ...data } = item;
    const menuItem = await prisma.menuItem.create({
      data: {
        ...data,
        restaurantId: restaurants[restaurantSlug].id,
        available: true,
        featured: data.featured ?? false,
      },
    });
    created.push(menuItem);
  }
  return created;
}

async function seedBreads() {
  const breadsData = [
    {
      name: "Wheat Baguette Bread",
      slug: "wheat-baguette-bread",
      subtitle: "THE EVERYDAY CLASSIC",
      description:
        "A crisp-crusted wheat baguette with an open crumb — the everyday loaf for soups, stews, and simple sandwiches across Nigerian tables.",
      image: IMG.food.baguette,
      category: "Classic",
      number: 1,
      allergens: ["gluten"],
      portionNote: "One 250 g baguette serves 2–3 as a side",
      prepMinutes: 180,
      reference:
        "Inspired by French bakery technique adapted for Nigerian wheat flour humidity and ambient fermentation times common in Lagos kitchens.",
      ingredients: [
        { ingredient: "White flour", quantity: 140, unit: "g", sortOrder: 0 },
        { ingredient: "Wholemeal flour", quantity: 60, unit: "g", sortOrder: 1 },
        { ingredient: "Water", quantity: 136, unit: "g", sortOrder: 2 },
        { ingredient: "Yeast", quantity: 2, unit: "g", sortOrder: 3 },
        { ingredient: "Salt", quantity: 3, unit: "g", sortOrder: 4 },
      ],
      nutrition: {
        calories: 265,
        protein: 9.2,
        carbohydrates: 52,
        fat: 1.4,
        fibre: 3.1,
        sodium: 480,
        perNote: "Per modelled portion",
      },
      pairings: [
        {
          foodName: "Egusi Soup",
          description: "Tear warm baguette into the rich melon-seed stew instead of swallow for a lighter meal.",
          image: IMG.food.egusi,
          category: "Mains",
        },
        {
          foodName: "Pepper Soup",
          description: "Soak the crusty end into aromatic goat or fish pepper soup.",
          image: IMG.food.seafood,
          category: "Starters",
        },
        {
          foodName: "Avocado & Egg",
          description: "Toast slices and top with smashed avocado, soft egg, and chilli flakes.",
          image: IMG.food.salad,
          category: "Breakfast",
        },
      ],
    },
    {
      name: "Wrapped Baguette Bread",
      slug: "wrapped-baguette-bread",
      subtitle: "READY TO TAKE ALONG",
      description:
        "A portable baguette wrapped for travel — ideal for office lunches, road trips to Abuja, and picnic spreads with suya or shawarma fillings.",
      image: IMG.food.bread,
      category: "On-the-go",
      number: 2,
      allergens: ["gluten"],
      portionNote: "One wrapped loaf packs as a single hearty lunch",
      prepMinutes: 165,
      reference:
        "Designed for ChowSmart takeaway culture — shaped for wrapping without crushing the crumb, referencing West African street sandwich formats.",
      ingredients: [
        { ingredient: "Bread flour", quantity: 480, unit: "g", sortOrder: 0 },
        { ingredient: "Water", quantity: 340, unit: "g", sortOrder: 1 },
        { ingredient: "Olive oil", quantity: 20, unit: "g", sortOrder: 2 },
        { ingredient: "Instant yeast", quantity: 6, unit: "g", sortOrder: 3 },
        { ingredient: "Salt", quantity: 9, unit: "g", sortOrder: 4 },
        { ingredient: "Sugar", quantity: 8, unit: "g", sortOrder: 5 },
      ],
      nutrition: {
        calories: 275,
        protein: 8.8,
        carbohydrates: 51,
        fat: 3.2,
        fibre: 2.6,
        sodium: 460,
        perNote: "Per 100 g modelled portion",
      },
      pairings: [
        {
          foodName: "Chicken Shawarma",
          description: "Split and fill with garlicky shawarma, pickles, and cabbage.",
          image: IMG.food.shawarma,
          category: "Mains",
        },
        {
          foodName: "Beef Suya",
          description: "Layer suya strips with onion and tomato for a spicy packed lunch.",
          image: IMG.food.suya,
          category: "Mains",
        },
        {
          foodName: "Hummus & Salad",
          description: "Spread hummus and pack cucumber, tomato, and olives for a cooler picnic.",
          image: IMG.food.salad,
          category: "Sides",
        },
      ],
    },
    {
      name: "Honey-Creamed Bread",
      slug: "honey-creamed-bread",
      subtitle: "A GOLDEN CENTRE",
      description:
        "A soft enriched loaf with a golden honey-cream swirl through the centre — gently sweet, fragrant with vanilla, and perfect with morning tea.",
      image: IMG.food.honeyBread,
      category: "Enriched",
      number: 3,
      allergens: ["gluten", "dairy", "egg"],
      portionNote: "One loaf yields about 10 thick slices",
      prepMinutes: 210,
      reference:
        "Draws on Nigerian soft bread traditions and European brioche technique — honey from local apiaries sweetens the cream filling.",
      ingredients: [
        { ingredient: "Bread flour", quantity: 450, unit: "g", sortOrder: 0 },
        { ingredient: "Milk", quantity: 180, unit: "g", sortOrder: 1 },
        { ingredient: "Butter", quantity: 60, unit: "g", sortOrder: 2 },
        { ingredient: "Egg", quantity: 50, unit: "g", sortOrder: 3 },
        { ingredient: "Honey", quantity: 80, unit: "g", sortOrder: 4 },
        { ingredient: "Cream cheese", quantity: 100, unit: "g", sortOrder: 5 },
        { ingredient: "Yeast", quantity: 7, unit: "g", sortOrder: 6 },
        { ingredient: "Salt", quantity: 7, unit: "g", sortOrder: 7 },
      ],
      nutrition: {
        calories: 320,
        protein: 8.5,
        carbohydrates: 48,
        fat: 10.5,
        fibre: 1.8,
        sodium: 340,
        perNote: "Per 100 g modelled portion",
      },
      pairings: [
        {
          foodName: "Fresh Fruit Plate",
          description: "Serve warm slices with pineapple, mango, and pawpaw.",
          image: IMG.food.salad,
          category: "Breakfast",
        },
        {
          foodName: "Yoghurt & Honey",
          description: "Toast lightly and spoon over thick yoghurt with extra honey.",
          image: IMG.food.dessert,
          category: "Desserts",
        },
        {
          foodName: "Black Tea",
          description: "A classic Lagos breakfast pairing — soft bread with strong tea.",
          image: IMG.food.drink,
          category: "Drinks",
        },
      ],
    },
    {
      name: "Chocolate-Creamed Bread",
      slug: "chocolate-creamed-bread",
      subtitle: "RICH & CHOCOLATE FILLED",
      description:
        "An indulgent soft loaf swirled with dark chocolate cream — rich without being heavy, made for weekend brunch and dessert boards.",
      image: IMG.food.chocolateBread,
      category: "Enriched",
      number: 4,
      allergens: ["gluten", "dairy", "egg"],
      portionNote: "Best shared — one loaf cuts into 8–10 dessert portions",
      prepMinutes: 220,
      reference:
        "ChowSmart’s chocolate-cream loaf balances cocoa intensity with soft crumb structure suited to warm Nigerian climates.",
      ingredients: [
        { ingredient: "Bread flour", quantity: 440, unit: "g", sortOrder: 0 },
        { ingredient: "Cocoa powder", quantity: 30, unit: "g", sortOrder: 1 },
        { ingredient: "Milk", quantity: 170, unit: "g", sortOrder: 2 },
        { ingredient: "Butter", quantity: 70, unit: "g", sortOrder: 3 },
        { ingredient: "Egg", quantity: 50, unit: "g", sortOrder: 4 },
        { ingredient: "Dark chocolate", quantity: 120, unit: "g", sortOrder: 5 },
        { ingredient: "Sugar", quantity: 60, unit: "g", sortOrder: 6 },
        { ingredient: "Yeast", quantity: 7, unit: "g", sortOrder: 7 },
        { ingredient: "Salt", quantity: 6, unit: "g", sortOrder: 8 },
      ],
      nutrition: {
        calories: 355,
        protein: 8.1,
        carbohydrates: 46,
        fat: 15.2,
        fibre: 3.4,
        sodium: 300,
        perNote: "Per 100 g modelled portion",
      },
      pairings: [
        {
          foodName: "Vanilla Ice Cream",
          description: "Warm a thick slice and top with a scoop of vanilla ice cream.",
          image: IMG.food.dessert,
          category: "Desserts",
        },
        {
          foodName: "Espresso",
          description: "The bitterness of espresso cuts through the chocolate cream swirl.",
          image: IMG.food.drink,
          category: "Drinks",
        },
        {
          foodName: "Berries",
          description: "Fresh strawberries or raspberries brighten the rich filling.",
          image: IMG.food.salad,
          category: "Sides",
        },
      ],
    },
    {
      name: "Coconut-Creamed Bread",
      slug: "coconut-creamed-bread",
      subtitle: "A CREAMY COCONUT SWIRL",
      description:
        "A tropical enriched bread with a creamy coconut swirl — echoing coastal Nigerian coconut sweets with a soft bakery crumb.",
      image: IMG.food.coconutBread,
      category: "Enriched",
      number: 5,
      allergens: ["gluten", "dairy", "egg"],
      portionNote: "One loaf serves 8 as a tea-time treat",
      prepMinutes: 200,
      reference:
        "Coconut milk and grated coconut from southern Nigeria flavour this swirl loaf — a ChowSmart signature tropical bake.",
      ingredients: [
        { ingredient: "Bread flour", quantity: 450, unit: "g", sortOrder: 0 },
        { ingredient: "Coconut milk", quantity: 200, unit: "g", sortOrder: 1 },
        { ingredient: "Desiccated coconut", quantity: 60, unit: "g", sortOrder: 2 },
        { ingredient: "Butter", quantity: 50, unit: "g", sortOrder: 3 },
        { ingredient: "Egg", quantity: 50, unit: "g", sortOrder: 4 },
        { ingredient: "Sugar", quantity: 50, unit: "g", sortOrder: 5 },
        { ingredient: "Yeast", quantity: 7, unit: "g", sortOrder: 6 },
        { ingredient: "Salt", quantity: 7, unit: "g", sortOrder: 7 },
      ],
      nutrition: {
        calories: 335,
        protein: 7.6,
        carbohydrates: 44,
        fat: 14.8,
        fibre: 3.8,
        sodium: 320,
        perNote: "Per 100 g modelled portion",
      },
      pairings: [
        {
          foodName: "Grilled Prawns",
          description: "Unexpected but lovely — coconut bread alongside garlicky prawns.",
          image: IMG.food.seafood,
          category: "Mains",
        },
        {
          foodName: "Pineapple Salsa",
          description: "Bright pineapple salsa cuts the creamy coconut swirl.",
          image: IMG.food.salad,
          category: "Sides",
        },
        {
          foodName: "Coconut Water",
          description: "Keep the tropical theme with chilled coconut water.",
          image: IMG.food.drink,
          category: "Drinks",
        },
      ],
    },
  ];

  const breads = [];
  for (const b of breadsData) {
    const { ingredients, nutrition, pairings, ...data } = b;
    const bread = await prisma.bread.create({
      data: {
        ...data,
        featured: true,
        ingredients: { create: ingredients },
        nutrition: { create: nutrition },
        pairings: { create: pairings },
      },
    });
    breads.push(bread);
  }
  return Object.fromEntries(breads.map((b) => [b.slug, b]));
}

async function seedRecipes(cuisines: Record<string, { id: string; slug: string }>) {
  const recipesData = [
    {
      name: "Smoky Party Jollof Rice",
      slug: "smoky-party-jollof-rice",
      description: "The celebration staple — tomato-pepper base, long-grain rice, and that unmistakable party smokiness.",
      image: IMG.food.jollof,
      prepTime: 25,
      cookTime: 50,
      servings: 6,
      difficulty: Difficulty.MEDIUM,
      instructions: [
        "Blend tomatoes, red peppers, scotch bonnet, and onion into a smooth puree.",
        "Fry the puree in oil until the oil floats and the raw taste is gone.",
        "Add tomato paste, thyme, curry, bay leaf, and stock; simmer 10 minutes.",
        "Stir in washed rice, cover tightly, and steam until tender, adding stock as needed.",
        "Finish over low heat for light smokiness; rest 5 minutes before fluffing.",
      ],
      calories: 480,
      protein: 10,
      carbohydrates: 78,
      fat: 14,
      allergens: [],
      dietaryTags: ["gluten-free", "dairy-free"],
      cuisineSlug: "nigerian",
      featured: true,
      ingredients: [
        { ingredient: "Long-grain parboiled rice", quantity: "4", unit: "cups", sortOrder: 0 },
        { ingredient: "Tomatoes", quantity: "6", unit: "large", sortOrder: 1 },
        { ingredient: "Red bell peppers", quantity: "3", unit: "whole", sortOrder: 2 },
        { ingredient: "Scotch bonnet", quantity: "2", unit: "pieces", sortOrder: 3 },
        { ingredient: "Onion", quantity: "2", unit: "large", sortOrder: 4 },
        { ingredient: "Chicken stock", quantity: "4", unit: "cups", sortOrder: 5 },
      ],
    },
    {
      name: "Classic Beef Suya",
      slug: "classic-beef-suya",
      description: "Street-style suya with homemade yaji spice — fiery, nutty, and best eaten hot off the skewer.",
      image: IMG.food.suya,
      prepTime: 40,
      cookTime: 15,
      servings: 4,
      difficulty: Difficulty.EASY,
      instructions: [
        "Slice beef thinly against the grain and thread onto skewers.",
        "Mix groundnut powder, ginger, garlic, cayenne, paprika, and salt for yaji.",
        "Coat beef generously and rest 30 minutes.",
        "Grill over charcoal or high heat, turning until charred at the edges.",
        "Dust with more yaji and serve with onion and tomato.",
      ],
      calories: 390,
      protein: 36,
      carbohydrates: 8,
      fat: 24,
      allergens: ["peanuts"],
      dietaryTags: ["high-protein", "gluten-free"],
      cuisineSlug: "nigerian",
      featured: true,
      ingredients: [
        { ingredient: "Beef sirloin", quantity: "800", unit: "g", sortOrder: 0 },
        { ingredient: "Roasted groundnut powder", quantity: "100", unit: "g", sortOrder: 1 },
        { ingredient: "Ginger powder", quantity: "2", unit: "tsp", sortOrder: 2 },
        { ingredient: "Cayenne", quantity: "1", unit: "tsp", sortOrder: 3 },
        { ingredient: "Onion", quantity: "1", unit: "large", sortOrder: 4 },
      ],
    },
    {
      name: "Egusi Soup",
      slug: "egusi-soup",
      description: "Ground melon seeds simmered with leafy greens, palm oil, and assorted proteins.",
      image: IMG.food.egusi,
      prepTime: 30,
      cookTime: 45,
      servings: 6,
      difficulty: Difficulty.MEDIUM,
      instructions: [
        "Toast and grind egusi seeds, or use pre-ground egusi.",
        "Season and boil meats and stockfish until tender; reserve stock.",
        "Fry blended pepper and onion in palm oil.",
        "Add egusi paste and cook until oil rises, then add stock and proteins.",
        "Fold in spinach or ugu and simmer briefly; adjust salt and pepper.",
      ],
      calories: 520,
      protein: 28,
      carbohydrates: 12,
      fat: 40,
      allergens: ["fish"],
      dietaryTags: ["gluten-free"],
      cuisineSlug: "nigerian",
      featured: true,
      ingredients: [
        { ingredient: "Egusi (ground)", quantity: "2", unit: "cups", sortOrder: 0 },
        { ingredient: "Palm oil", quantity: "1/2", unit: "cup", sortOrder: 1 },
        { ingredient: "Assorted beef", quantity: "500", unit: "g", sortOrder: 2 },
        { ingredient: "Stockfish", quantity: "100", unit: "g", sortOrder: 3 },
        { ingredient: "Ugu / spinach", quantity: "4", unit: "cups", sortOrder: 4 },
      ],
    },
    {
      name: "Pounded Yam",
      slug: "pounded-yam",
      description: "Smooth, stretchy pounded yam — the classic swallow for Nigerian soups.",
      image: IMG.food.poundedYam,
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      difficulty: Difficulty.EASY,
      instructions: [
        "Peel and cube white yam; rinse well.",
        "Boil until soft enough to mash easily.",
        "Pound or blend with a little cooking water until stretchy and lump-free.",
        "Shape into smooth mounds and serve immediately with soup.",
      ],
      calories: 340,
      protein: 4,
      carbohydrates: 80,
      fat: 0.5,
      allergens: [],
      dietaryTags: ["vegan", "gluten-free", "dairy-free"],
      cuisineSlug: "nigerian",
      featured: false,
      ingredients: [
        { ingredient: "White yam", quantity: "1.2", unit: "kg", sortOrder: 0 },
        { ingredient: "Water", quantity: "as needed", unit: "", sortOrder: 1 },
        { ingredient: "Salt", quantity: "1", unit: "pinch", sortOrder: 2 },
      ],
    },
    {
      name: "Chicken Shawarma at Home",
      slug: "chicken-shawarma-at-home",
      description: "Spice-rubbed chicken thighs roasted and wrapped with garlic sauce and pickles.",
      image: IMG.food.shawarma,
      prepTime: 20,
      cookTime: 35,
      servings: 4,
      difficulty: Difficulty.EASY,
      breadSlug: "wrapped-baguette-bread",
      instructions: [
        "Marinate chicken in yoghurt, garlic, cumin, paprika, and lemon for at least 1 hour.",
        "Roast or pan-sear until cooked through and lightly charred.",
        "Slice thinly and warm flatbread or wrapped baguette.",
        "Assemble with garlic sauce, cabbage, pickles, and fries.",
      ],
      calories: 610,
      protein: 38,
      carbohydrates: 48,
      fat: 28,
      allergens: ["dairy", "gluten"],
      dietaryTags: ["high-protein"],
      cuisineSlug: "mediterranean",
      featured: true,
      ingredients: [
        { ingredient: "Chicken thighs", quantity: "700", unit: "g", sortOrder: 0 },
        { ingredient: "Yoghurt", quantity: "1/2", unit: "cup", sortOrder: 1 },
        { ingredient: "Garlic", quantity: "4", unit: "cloves", sortOrder: 2 },
        { ingredient: "Flatbread or baguette", quantity: "4", unit: "pieces", sortOrder: 3 },
        { ingredient: "Pickles", quantity: "1", unit: "cup", sortOrder: 4 },
      ],
    },
    {
      name: "Homemade Margherita Pizza",
      slug: "homemade-margherita-pizza",
      description: "Thin-crust pizza with tomato, mozzarella, and basil — weeknight Italian at home.",
      image: IMG.food.pizza,
      prepTime: 90,
      cookTime: 12,
      servings: 2,
      difficulty: Difficulty.MEDIUM,
      instructions: [
        "Mix flour, water, yeast, and salt; knead until smooth and prove 1 hour.",
        "Shape into two thin bases.",
        "Spread crushed tomato, tear mozzarella over the top, and drizzle olive oil.",
        "Bake on a preheated stone or tray at the highest oven setting until blistered.",
        "Finish with fresh basil.",
      ],
      calories: 640,
      protein: 24,
      carbohydrates: 78,
      fat: 24,
      allergens: ["gluten", "dairy"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "italian",
      featured: false,
      ingredients: [
        { ingredient: "00 flour or bread flour", quantity: "300", unit: "g", sortOrder: 0 },
        { ingredient: "Water", quantity: "190", unit: "g", sortOrder: 1 },
        { ingredient: "Mozzarella", quantity: "200", unit: "g", sortOrder: 2 },
        { ingredient: "Tomato passata", quantity: "150", unit: "g", sortOrder: 3 },
        { ingredient: "Fresh basil", quantity: "1", unit: "handful", sortOrder: 4 },
      ],
    },
    {
      name: "Garlic Butter Pasta",
      slug: "garlic-butter-pasta",
      description: "Quick spaghetti with garlic, chilli, butter, and parsley — ready in under 20 minutes.",
      image: IMG.food.pasta,
      prepTime: 5,
      cookTime: 15,
      servings: 2,
      difficulty: Difficulty.EASY,
      breadSlug: "wheat-baguette-bread",
      instructions: [
        "Cook spaghetti in salted water until al dente; reserve pasta water.",
        "Gently fry sliced garlic and chilli in butter until fragrant.",
        "Toss pasta with the garlic butter, adding pasta water to emulsify.",
        "Finish with parsley and black pepper; serve with baguette.",
      ],
      calories: 520,
      protein: 14,
      carbohydrates: 68,
      fat: 20,
      allergens: ["gluten", "dairy"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "italian",
      featured: false,
      ingredients: [
        { ingredient: "Spaghetti", quantity: "250", unit: "g", sortOrder: 0 },
        { ingredient: "Butter", quantity: "40", unit: "g", sortOrder: 1 },
        { ingredient: "Garlic", quantity: "4", unit: "cloves", sortOrder: 2 },
        { ingredient: "Chilli flakes", quantity: "1/2", unit: "tsp", sortOrder: 3 },
        { ingredient: "Parsley", quantity: "2", unit: "tbsp", sortOrder: 4 },
      ],
    },
    {
      name: "Smash Burger Night",
      slug: "smash-burger-night",
      description: "Thin, crispy-edged smash burgers with cheddar and house sauce.",
      image: IMG.food.burger,
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      difficulty: Difficulty.EASY,
      instructions: [
        "Form loose beef balls; do not overwork.",
        "Smash hard onto a hot pan; season with salt and pepper.",
        "Flip once, top with cheddar, and melt briefly.",
        "Toast buns and assemble with sauce, pickles, and onion.",
      ],
      calories: 780,
      protein: 42,
      carbohydrates: 36,
      fat: 48,
      allergens: ["gluten", "dairy"],
      dietaryTags: ["high-protein"],
      cuisineSlug: "american",
      featured: false,
      ingredients: [
        { ingredient: "Minced beef (80/20)", quantity: "600", unit: "g", sortOrder: 0 },
        { ingredient: "Burger buns", quantity: "4", unit: "pieces", sortOrder: 1 },
        { ingredient: "Cheddar slices", quantity: "4", unit: "slices", sortOrder: 2 },
        { ingredient: "Pickles", quantity: "8", unit: "slices", sortOrder: 3 },
        { ingredient: "House sauce", quantity: "4", unit: "tbsp", sortOrder: 4 },
      ],
    },
    {
      name: "Wok Egg Fried Rice",
      slug: "wok-egg-fried-rice",
      description: "Day-old rice wok-fried with egg, spring onion, and light soy — a weeknight staple.",
      image: IMG.food.friedRice,
      prepTime: 10,
      cookTime: 10,
      servings: 3,
      difficulty: Difficulty.EASY,
      instructions: [
        "Scramble eggs in a hot wok and set aside.",
        "Stir-fry garlic and spring onion in oil.",
        "Add cold cooked rice and break up clumps.",
        "Season with soy sauce; return eggs and toss well.",
      ],
      calories: 430,
      protein: 14,
      carbohydrates: 62,
      fat: 14,
      allergens: ["egg", "soy"],
      dietaryTags: ["dairy-free"],
      cuisineSlug: "chinese",
      featured: false,
      ingredients: [
        { ingredient: "Cooked rice (day-old)", quantity: "4", unit: "cups", sortOrder: 0 },
        { ingredient: "Eggs", quantity: "3", unit: "large", sortOrder: 1 },
        { ingredient: "Spring onion", quantity: "4", unit: "stalks", sortOrder: 2 },
        { ingredient: "Light soy sauce", quantity: "2", unit: "tbsp", sortOrder: 3 },
        { ingredient: "Garlic", quantity: "2", unit: "cloves", sortOrder: 4 },
      ],
    },
    {
      name: "Butter Chicken",
      slug: "butter-chicken",
      description: "Tender chicken in a creamy tomato-cashew gravy — milder spice, deep flavour.",
      image: IMG.food.curry,
      prepTime: 30,
      cookTime: 40,
      servings: 4,
      difficulty: Difficulty.MEDIUM,
      instructions: [
        "Marinate chicken in yoghurt and tandoori spices; grill or roast until charred.",
        "Blend soaked cashews with tomato puree for a smooth base.",
        "Cook the base with butter, garlic, and garam masala.",
        "Add cream and grilled chicken; simmer gently until thick.",
        "Serve with naan or rice.",
      ],
      calories: 650,
      protein: 38,
      carbohydrates: 22,
      fat: 44,
      allergens: ["dairy", "tree nuts"],
      dietaryTags: ["gluten-free"],
      cuisineSlug: "indian",
      featured: true,
      ingredients: [
        { ingredient: "Chicken thighs", quantity: "700", unit: "g", sortOrder: 0 },
        { ingredient: "Tomato puree", quantity: "400", unit: "g", sortOrder: 1 },
        { ingredient: "Cashews", quantity: "50", unit: "g", sortOrder: 2 },
        { ingredient: "Cream", quantity: "100", unit: "ml", sortOrder: 3 },
        { ingredient: "Butter", quantity: "40", unit: "g", sortOrder: 4 },
      ],
    },
    {
      name: "Grilled Tilapia with Pepper Sauce",
      slug: "grilled-tilapia-pepper-sauce",
      description: "Whole tilapia grilled until crisp-skinned and served with fiery Nigerian pepper sauce.",
      image: IMG.food.seafood,
      prepTime: 20,
      cookTime: 25,
      servings: 2,
      difficulty: Difficulty.MEDIUM,
      breadSlug: "wheat-baguette-bread",
      instructions: [
        "Score the tilapia and season with salt, ginger, and garlic.",
        "Grill or oven-roast until flesh flakes easily.",
        "Blend tomatoes, peppers, and onion; fry into a thick pepper sauce.",
        "Serve fish with sauce, plantain, and baguette for dipping.",
      ],
      calories: 470,
      protein: 42,
      carbohydrates: 18,
      fat: 26,
      allergens: ["fish"],
      dietaryTags: ["high-protein", "dairy-free"],
      cuisineSlug: "african",
      featured: false,
      ingredients: [
        { ingredient: "Whole tilapia", quantity: "2", unit: "medium", sortOrder: 0 },
        { ingredient: "Scotch bonnet", quantity: "2", unit: "pieces", sortOrder: 1 },
        { ingredient: "Tomatoes", quantity: "3", unit: "large", sortOrder: 2 },
        { ingredient: "Onion", quantity: "1", unit: "large", sortOrder: 3 },
        { ingredient: "Plantain", quantity: "2", unit: "ripe", sortOrder: 4 },
      ],
    },
    {
      name: "Mediterranean Mezze Board",
      slug: "mediterranean-mezze-board",
      description: "Hummus, baba ganoush, olives, and flatbread for easy sharing.",
      image: IMG.food.salad,
      prepTime: 35,
      cookTime: 30,
      servings: 6,
      difficulty: Difficulty.MEDIUM,
      breadSlug: "wheat-baguette-bread",
      instructions: [
        "Blend chickpeas, tahini, lemon, and garlic into hummus.",
        "Roast aubergine until soft; mash with tahini and olive oil for baba ganoush.",
        "Warm baguette slices and arrange olives and feta.",
        "Drizzle everything with olive oil and serve family-style.",
      ],
      calories: 380,
      protein: 12,
      carbohydrates: 32,
      fat: 22,
      allergens: ["sesame", "dairy", "gluten"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "mediterranean",
      featured: false,
      ingredients: [
        { ingredient: "Chickpeas", quantity: "400", unit: "g", sortOrder: 0 },
        { ingredient: "Tahini", quantity: "3", unit: "tbsp", sortOrder: 1 },
        { ingredient: "Aubergine", quantity: "2", unit: "large", sortOrder: 2 },
        { ingredient: "Feta", quantity: "150", unit: "g", sortOrder: 3 },
        { ingredient: "Olives", quantity: "1", unit: "cup", sortOrder: 4 },
      ],
    },
    {
      name: "Honey Cream Toast",
      slug: "honey-cream-toast",
      description: "Thick slices of honey-creamed bread, lightly toasted and finished with yoghurt and fruit.",
      image: IMG.food.honeyBread,
      prepTime: 5,
      cookTime: 5,
      servings: 2,
      difficulty: Difficulty.EASY,
      breadSlug: "honey-creamed-bread",
      instructions: [
        "Slice honey-creamed bread thickly.",
        "Toast until the edges are golden and the cream centre softens.",
        "Top with thick yoghurt, fresh mango, and a drizzle of honey.",
        "Serve immediately with black tea.",
      ],
      calories: 410,
      protein: 11,
      carbohydrates: 58,
      fat: 15,
      allergens: ["gluten", "dairy", "egg"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "continental",
      featured: false,
      ingredients: [
        { ingredient: "Honey-creamed bread", quantity: "4", unit: "slices", sortOrder: 0 },
        { ingredient: "Greek yoghurt", quantity: "1", unit: "cup", sortOrder: 1 },
        { ingredient: "Mango", quantity: "1", unit: "ripe", sortOrder: 2 },
        { ingredient: "Honey", quantity: "2", unit: "tbsp", sortOrder: 3 },
      ],
    },
    {
      name: "Chocolate Cream Bread Pudding",
      slug: "chocolate-cream-bread-pudding",
      description: "Day-old chocolate-creamed bread baked into a custard pudding with dark cocoa.",
      image: IMG.food.chocolateBread,
      prepTime: 20,
      cookTime: 40,
      servings: 6,
      difficulty: Difficulty.ADVANCED,
      breadSlug: "chocolate-creamed-bread",
      instructions: [
        "Cube chocolate-creamed bread and arrange in a buttered baking dish.",
        "Whisk milk, cream, eggs, sugar, and cocoa into a custard.",
        "Pour over bread and soak 20 minutes.",
        "Bake until set and slightly puffed; rest before serving warm.",
      ],
      calories: 450,
      protein: 10,
      carbohydrates: 52,
      fat: 22,
      allergens: ["gluten", "dairy", "egg"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "continental",
      featured: true,
      ingredients: [
        { ingredient: "Chocolate-creamed bread", quantity: "400", unit: "g", sortOrder: 0 },
        { ingredient: "Milk", quantity: "300", unit: "ml", sortOrder: 1 },
        { ingredient: "Cream", quantity: "150", unit: "ml", sortOrder: 2 },
        { ingredient: "Eggs", quantity: "3", unit: "large", sortOrder: 3 },
        { ingredient: "Cocoa powder", quantity: "2", unit: "tbsp", sortOrder: 4 },
      ],
    },
    {
      name: "Coconut Swirl French Toast",
      slug: "coconut-swirl-french-toast",
      description: "Coconut-creamed bread dipped in coconut-milk custard and pan-fried golden.",
      image: IMG.food.coconutBread,
      prepTime: 10,
      cookTime: 15,
      servings: 3,
      difficulty: Difficulty.EASY,
      breadSlug: "coconut-creamed-bread",
      instructions: [
        "Whisk eggs, coconut milk, vanilla, and a pinch of salt.",
        "Dip thick slices of coconut-creamed bread until soaked.",
        "Pan-fry in butter until both sides are deep golden.",
        "Serve with pineapple and toasted coconut flakes.",
      ],
      calories: 430,
      protein: 12,
      carbohydrates: 48,
      fat: 20,
      allergens: ["gluten", "dairy", "egg"],
      dietaryTags: ["vegetarian"],
      cuisineSlug: "african",
      featured: false,
      ingredients: [
        { ingredient: "Coconut-creamed bread", quantity: "6", unit: "slices", sortOrder: 0 },
        { ingredient: "Eggs", quantity: "3", unit: "large", sortOrder: 1 },
        { ingredient: "Coconut milk", quantity: "150", unit: "ml", sortOrder: 2 },
        { ingredient: "Butter", quantity: "30", unit: "g", sortOrder: 3 },
        { ingredient: "Pineapple", quantity: "1", unit: "cup", sortOrder: 4 },
      ],
    },
    {
      name: "Ofada Rice & Ayamase Stew",
      slug: "ofada-rice-ayamase-stew",
      description: "Local ofada rice with green pepper stew — a Lagos favourite with bold heat.",
      image: IMG.food.jollof,
      prepTime: 25,
      cookTime: 50,
      servings: 4,
      difficulty: Difficulty.ADVANCED,
      instructions: [
        "Wash ofada rice thoroughly and boil until tender; drain.",
        "Blend green peppers, scotch bonnet, and onion.",
        "Bleach palm oil carefully, then fry the green pepper mix until thick.",
        "Add locust bean, seasoned meats, and simmer into ayamase.",
        "Serve stew over ofada rice with boiled egg.",
      ],
      calories: 620,
      protein: 26,
      carbohydrates: 70,
      fat: 28,
      allergens: ["egg"],
      dietaryTags: ["gluten-free", "dairy-free"],
      cuisineSlug: "nigerian",
      featured: false,
      ingredients: [
        { ingredient: "Ofada rice", quantity: "3", unit: "cups", sortOrder: 0 },
        { ingredient: "Green bell peppers", quantity: "6", unit: "large", sortOrder: 1 },
        { ingredient: "Palm oil", quantity: "1/2", unit: "cup", sortOrder: 2 },
        { ingredient: "Assorted meat", quantity: "500", unit: "g", sortOrder: 3 },
        { ingredient: "Locust bean (iru)", quantity: "2", unit: "tbsp", sortOrder: 4 },
      ],
    },
    {
      name: "Salmon Teriyaki Bowl",
      slug: "salmon-teriyaki-bowl",
      description: "Pan-seared salmon glazed with homemade teriyaki over sushi rice and cucumber.",
      image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&q=80",
      prepTime: 20,
      cookTime: 20,
      servings: 2,
      difficulty: Difficulty.MEDIUM,
      instructions: [
        "Cook sushi rice and season lightly with rice vinegar.",
        "Simmer soy sauce, mirin, sake, and sugar into a glossy teriyaki glaze.",
        "Pan-sear salmon skin-side down until crisp; flip and brush with glaze.",
        "Serve over rice with cucumber, sesame seeds, and extra glaze.",
      ],
      calories: 540,
      protein: 36,
      carbohydrates: 48,
      fat: 22,
      allergens: ["fish", "soy"],
      dietaryTags: ["dairy-free", "high-protein"],
      cuisineSlug: "japanese",
      featured: true,
      ingredients: [
        { ingredient: "Salmon fillets", quantity: "2", unit: "pieces", sortOrder: 0 },
        { ingredient: "Sushi rice", quantity: "1.5", unit: "cups", sortOrder: 1 },
        { ingredient: "Soy sauce", quantity: "3", unit: "tbsp", sortOrder: 2 },
        { ingredient: "Mirin", quantity: "2", unit: "tbsp", sortOrder: 3 },
        { ingredient: "Cucumber", quantity: "1", unit: "medium", sortOrder: 4 },
      ],
    },
  ];

  const recipes = [];
  for (const r of recipesData) {
    const { cuisineSlug, ingredients, ...data } = r;
    const recipe = await prisma.recipe.create({
      data: {
        ...data,
        cuisineId: cuisines[cuisineSlug].id,
        ingredients: { create: ingredients },
      },
    });
    recipes.push(recipe);
  }
  return recipes;
}

async function seedMenuPlan(
  userId: string,
  menuItems: Array<{ id: string; name: string; calories: number | null; price: number }>,
  breads: Record<string, { id: string; name: string }>,
  recipes: Array<{ id: string; name: string; calories: number | null; slug: string }>
) {
  const jollof = menuItems.find((m) => m.name === "Party Jollof Rice")!;
  const suya = menuItems.find((m) => m.name === "Classic Beef Suya")!;
  const zobo = menuItems.find((m) => m.name === "Zobo Drink")!;
  const baguette = breads["wheat-baguette-bread"];
  const shawarmaRecipe = recipes.find((r) => r.slug === "chicken-shawarma-at-home")!;

  await prisma.menuPlan.create({
    data: {
      userId,
      name: "Sunday Lagos Feast",
      description: "A relaxed weekend menu mixing party jollof, suya, and soft baguette sides.",
      items: {
        create: [
          {
            itemType: MenuItemType.MENU_ITEM,
            itemId: jollof.id,
            name: jollof.name,
            quantity: 2,
            notes: "Ask for extra smoky crust",
            sortOrder: 0,
            calories: jollof.calories,
            price: jollof.price,
          },
          {
            itemType: MenuItemType.MENU_ITEM,
            itemId: suya.id,
            name: suya.name,
            quantity: 1,
            notes: "Medium spice",
            sortOrder: 1,
            calories: suya.calories,
            price: suya.price,
          },
          {
            itemType: MenuItemType.MENU_ITEM,
            itemId: zobo.id,
            name: zobo.name,
            quantity: 3,
            sortOrder: 2,
            calories: zobo.calories,
            price: zobo.price,
          },
          {
            itemType: MenuItemType.BREAD,
            itemId: baguette.id,
            name: baguette.name,
            quantity: 1,
            notes: "Warm before serving",
            sortOrder: 3,
            calories: 265,
            price: 0,
          },
          {
            itemType: MenuItemType.RECIPE,
            itemId: shawarmaRecipe.id,
            name: shawarmaRecipe.name,
            quantity: 1,
            notes: "Prep marinade the night before",
            sortOrder: 4,
            calories: shawarmaRecipe.calories,
            price: null,
          },
        ],
      },
    },
  });
}

export async function main() {
  console.log("Seeding ChowSmart database...");

  await clearData();
  console.log("Cleared existing data.");

  const { user } = await seedUsers();
  const cuisines = await seedCuisines();
  const restaurants = await seedRestaurants(cuisines);
  const menuItems = await seedMenuItems(restaurants);
  const breads = await seedBreads();
  const recipes = await seedRecipes(cuisines);
  await seedMenuPlan(user.id, menuItems, breads, recipes);

  const counts = {
    users: await prisma.user.count(),
    cuisines: await prisma.cuisine.count(),
    restaurants: await prisma.restaurant.count(),
    restaurantCuisines: await prisma.restaurantCuisine.count(),
    menuItems: await prisma.menuItem.count(),
    breads: await prisma.bread.count(),
    breadIngredients: await prisma.breadIngredient.count(),
    breadNutrition: await prisma.breadNutrition.count(),
    pairings: await prisma.pairing.count(),
    recipes: await prisma.recipe.count(),
    recipeIngredients: await prisma.recipeIngredient.count(),
    menuPlans: await prisma.menuPlan.count(),
    menuPlanItems: await prisma.menuPlanItem.count(),
  };

  console.log("Seed complete. Counts:");
  for (const [key, value] of Object.entries(counts)) {
    console.log(`  ${key}: ${value}`);
  }

  return counts;
}

main()
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
